# These are supported funding model platforms

github: [lkjh-maker] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2, user3, user4]
patreon: lkjh-maker # Replace with a single Patreon username
open_collective: lkjh-maker # Replace with a single Open Collective name
ko_fi: lkjh-maker # Replace with a single Ko-fi username
tidelift: lkjh-maker # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: lkjh-maker # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: lkjh-maker # Replace with a single Liberapay username
issuehunt: lkjh-maker # Replace with a single IssueHunt username
otechie: lkjh-maker # Replace with a single Otechie username
custom: https://lkjh-maker.com/support # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2', 'link3', 'link4']
